"""Simulation interfaces and typed request models."""

from .ansys_simulator import AnsysSimulator
from .drivenmodal import (
    CapacitanceExtractionRequest,
    CapacitanceExtractionResult,
    CoupledSystemDrivenModalRequest,
    CoupledSystemDrivenModalResult,
    DrivenModalArtifactPolicy,
    DrivenModalLayerStackSpec,
    DrivenModalRunManifest,
    DrivenModalSetupSpec,
    DrivenModalSweepSpec,
    build_capacitance_request,
    build_coupled_system_request,
    build_segmented_coupled_system_requests,
    capacitance_comparison_table,
    capacitance_reference_summary,
    coupled_reference_summary,
    default_artifact_policy,
    default_capacitance_setup,
    default_capacitance_sweep,
    default_hamiltonian_setup,
    default_layer_stack,
    hamiltonian_comparison_table,
    maxwell_matrix_interpretation,
    segmented_hamiltonian_sweeps,
)

__all__ = [
    "AnsysSimulator",
    "CapacitanceExtractionRequest",
    "CapacitanceExtractionResult",
    "CoupledSystemDrivenModalRequest",
    "CoupledSystemDrivenModalResult",
    "DrivenModalArtifactPolicy",
    "DrivenModalLayerStackSpec",
    "DrivenModalRunManifest",
    "DrivenModalSetupSpec",
    "DrivenModalSweepSpec",
    "build_capacitance_request",
    "build_coupled_system_request",
    "build_segmented_coupled_system_requests",
    "capacitance_comparison_table",
    "capacitance_reference_summary",
    "coupled_reference_summary",
    "default_artifact_policy",
    "default_capacitance_setup",
    "default_capacitance_sweep",
    "default_hamiltonian_setup",
    "default_layer_stack",
    "hamiltonian_comparison_table",
    "maxwell_matrix_interpretation",
    "segmented_hamiltonian_sweeps",
]
