name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'fix'
      - 'docs'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
      - 'major'
      - 'break'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: 'No significant changes.'
template: |
  ## What's Changed

  $CHANGES

  ## Commits
  $COMMITS

  ### Contributors
  Thanks to these amazing contributors:

  $CONTRIBUTORS

commit-template: '- $MESSAGE ([$SHA]($URL))'
