name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
version-resolver:
  major:
    labels:
    - 'breaking'
  minor:
    labels:
    - 'feature'
  patch:
    labels:
    - 'fix'
    - 'bug'
    - 'docs'
template: |
  ## What's Changed
  $CHANGES
