"""Versioned layout artifacts and geometry inspection for SQuADDS."""

from .client import LayoutClient, LayoutReference
from .embeddings import (
    EMBEDDING_DIMENSIONS,
    EMBEDDING_FILENAMES,
    EMBEDDING_SCHEMA_FILENAMES,
    SHAPE_SIZE,
    STATIC_EMBEDDING_MODEL,
    LayoutEmbeddingClient,
    StaticEmbeddingClient,
    build_static_embeddings,
    parameter_sum,
    rasterize_functional_shape,
)
from .features import GEOMETRY_FEATURE_SCHEMA_VERSION, build_geometry_features, geometry_feature_record
from .manifest import (
    DEFAULT_LAYOUT_REPOSITORY,
    build_layout_record,
    canonical_design_id,
    infer_layout_component_name,
    parse_gds_polygons,
    parse_gds_summary,
    write_manifest,
)
from .transfer import (
    PartitionTransferStudy,
    SourceFeatureProjector,
    TransferRidgeRegressor,
    V0FeatureProjector,
    V0KernelFeatureProjector,
    V0PartitionTransferStudy,
    V0TransferLearningStudy,
    compress_v0_embeddings,
    evaluate_transfer_learning,
    mean_pairwise_cosine_similarity,
    regression_scores,
    required_target_samples,
    summarize_learning_curve,
    target_to_source_similarity,
)
from .universal_embeddings import (
    UNIVERSAL_EMBEDDING_DIMENSIONS,
    UNIVERSAL_EMBEDDING_MODEL,
    UNIVERSAL_EMBEDDING_SCHEMA_VERSION,
    UNIVERSAL_METRIC_NAMES,
    parameter_channels,
    universal_embedding_schema,
    write_universal_embedding_dataset,
)

__all__ = [
    "DEFAULT_LAYOUT_REPOSITORY",
    "EMBEDDING_FILENAMES",
    "EMBEDDING_SCHEMA_FILENAMES",
    "EMBEDDING_DIMENSIONS",
    "GEOMETRY_FEATURE_SCHEMA_VERSION",
    "LayoutClient",
    "LayoutEmbeddingClient",
    "LayoutReference",
    "PartitionTransferStudy",
    "SourceFeatureProjector",
    "build_layout_record",
    "SHAPE_SIZE",
    "STATIC_EMBEDDING_MODEL",
    "StaticEmbeddingClient",
    "UNIVERSAL_EMBEDDING_DIMENSIONS",
    "UNIVERSAL_EMBEDDING_MODEL",
    "UNIVERSAL_EMBEDDING_SCHEMA_VERSION",
    "UNIVERSAL_METRIC_NAMES",
    "TransferRidgeRegressor",
    "V0FeatureProjector",
    "V0KernelFeatureProjector",
    "V0PartitionTransferStudy",
    "V0TransferLearningStudy",
    "build_static_embeddings",
    "build_geometry_features",
    "canonical_design_id",
    "compress_v0_embeddings",
    "evaluate_transfer_learning",
    "mean_pairwise_cosine_similarity",
    "infer_layout_component_name",
    "geometry_feature_record",
    "parameter_sum",
    "parameter_channels",
    "rasterize_functional_shape",
    "regression_scores",
    "required_target_samples",
    "summarize_learning_curve",
    "target_to_source_similarity",
    "parse_gds_polygons",
    "parse_gds_summary",
    "write_manifest",
    "write_universal_embedding_dataset",
    "universal_embedding_schema",
]
