"""Driven-modal HFSS request, result, and utility models."""

from .capacitance import (
    capacitance_dataframe_from_y_sweep,
    capacitance_matrix_from_y,
    maxwell_capacitance_dataframe,
)
from .coupled_postprocess import (
    calculate_chi_hz,
    calculate_g_from_chi,
    calculate_kappa_hz,
    calculate_loaded_q,
    terminate_port_y,
    y_to_s,
)
from .design import create_multiplanar_design, write_qiskit_layer_stack_csv
from .extractors import (
    coupled_hamiltonian_from_prepared_runs,
    hamiltonian_from_summary_json,
    hamiltonian_from_summary_mapping,
    pair_capacitances_fF_from_run_dir,
    pair_capacitances_fF_from_y_frame,
)
from .hfss_data import network_from_parameter_dataframe, parameter_dataframe_to_tensor, write_touchstone_from_dataframe
from .layer_stack import LAYER_STACK_COLUMNS, build_layer_stack_dataframe, resolve_layer_stack
from .models import (
    CapacitanceExtractionRequest,
    CapacitanceExtractionResult,
    CoupledSystemDrivenModalRequest,
    CoupledSystemDrivenModalResult,
    DrivenModalArtifactPolicy,
    DrivenModalLayerStackSpec,
    DrivenModalPortSpec,
    DrivenModalRunManifest,
    DrivenModalSetupSpec,
    DrivenModalSweepSpec,
)
from .qubit_admittance import (
    bare_lj_to_ej_ghz,
    capacitance_to_ec_ghz,
    combine_port_admittance_with_jj,
    extract_parallel_mode_from_total_admittance,
    extract_qubit_from_port_admittance,
    jj_parallel_admittance,
    jj_parallel_impedance,
)
from .workflows import (
    build_capacitance_request,
    build_coupled_system_request,
    build_segmented_coupled_system_requests,
    capacitance_comparison_table,
    capacitance_reference_summary,
    coupled_reference_summary,
    default_artifact_policy,
    default_capacitance_setup,
    default_capacitance_sweep,
    default_hamiltonian_setup,
    default_hamiltonian_sweep,
    default_layer_stack,
    hamiltonian_comparison_table,
    maxwell_matrix_interpretation,
    segmented_hamiltonian_sweeps,
)

__all__ = [
    "LAYER_STACK_COLUMNS",
    "CapacitanceExtractionRequest",
    "CapacitanceExtractionResult",
    "calculate_chi_hz",
    "calculate_g_from_chi",
    "calculate_kappa_hz",
    "calculate_loaded_q",
    "capacitance_dataframe_from_y_sweep",
    "capacitance_matrix_from_y",
    "build_capacitance_request",
    "hamiltonian_from_summary_json",
    "hamiltonian_from_summary_mapping",
    "pair_capacitances_fF_from_run_dir",
    "pair_capacitances_fF_from_y_frame",
    "create_multiplanar_design",
    "CoupledSystemDrivenModalRequest",
    "CoupledSystemDrivenModalResult",
    "DrivenModalArtifactPolicy",
    "DrivenModalLayerStackSpec",
    "DrivenModalPortSpec",
    "DrivenModalRunManifest",
    "DrivenModalSetupSpec",
    "DrivenModalSweepSpec",
    "build_coupled_system_request",
    "build_segmented_coupled_system_requests",
    "bare_lj_to_ej_ghz",
    "build_layer_stack_dataframe",
    "capacitance_to_ec_ghz",
    "capacitance_comparison_table",
    "capacitance_reference_summary",
    "maxwell_capacitance_dataframe",
    "coupled_reference_summary",
    "default_artifact_policy",
    "default_capacitance_setup",
    "default_capacitance_sweep",
    "default_hamiltonian_setup",
    "default_hamiltonian_sweep",
    "default_layer_stack",
    "coupled_hamiltonian_from_prepared_runs",
    "network_from_parameter_dataframe",
    "parameter_dataframe_to_tensor",
    "combine_port_admittance_with_jj",
    "extract_parallel_mode_from_total_admittance",
    "extract_qubit_from_port_admittance",
    "hamiltonian_comparison_table",
    "jj_parallel_admittance",
    "jj_parallel_impedance",
    "maxwell_matrix_interpretation",
    "resolve_layer_stack",
    "segmented_hamiltonian_sweeps",
    "terminate_port_y",
    "write_qiskit_layer_stack_csv",
    "write_touchstone_from_dataframe",
    "y_to_s",
]
