#!/usr/bin/env python
"""Build the representation-first, executed planar embedding acceptance tutorial."""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

OUTPUT = Path("tutorials/Tutorial-24_Embedding_Representation_Acceptance.ipynb")


def md(source: str):
    return nbf.v4.new_markdown_cell(source.strip())


def code(source: str, *, hidden: bool = True):
    cell = nbf.v4.new_code_cell(source.strip())
    if hidden:
        cell["metadata"]["tags"] = ["hide-input"]
        cell["metadata"]["jupyter"] = {"source_hidden": True}
    return cell


cells = [
    md(r"""
# Tutorial 24: What does a geometry embedding need to remember?

Think about two superconducting layouts that differ only because one was drawn
30 µm to the right, or because the chip was rotated before export. Their
capacitances have not changed. Now widen the gap between their electrodes: the
capacitance *has* changed, so a useful representation must move.

That simple distinction drives this notebook. We treat the embedding like a
new measurement instrument and ask, in this order:

1. Does it ignore coordinate choices that the electrostatics cannot see?
2. Does it respond smoothly when a real capacitive control is changed?
3. Can it describe every conductor in a multi-terminal device?
4. Does geometric proximity track capacitance closely enough to help learning?
5. Does it reduce the number of new simulations needed for a new topology?

Each question starts with the physical thought experiment, states what is held
fixed, and only then shows the result. Red means a failed predeclared test, not
a software crash. A negative result is retained because it tells us what the
next representation or data sweep must fix.

The live report collapses implementation cells so the physical argument stays
readable. Open the `.ipynb` and reveal a cell whenever you want the exact code;
every displayed number and plot is still generated by that executed cell.

![Mermaid overview of the experiment logic](assets/tutorial24/experiment_logic.svg)

*[Mermaid source](assets/tutorial24/experiment_logic.mmd).*

The implemented scope is deliberately planar. A future layer-stack sidecar may
map GDS layers to physical planes, material, and thickness, but this notebook
does not manufacture flip-chip evidence from unswept scalar metadata.

The canonical v4 object is ragged: `N × 64` conductor-node features, `N × N ×
96` symmetric edge features, and 64 global features. This is necessary because
no fixed finite vector can preserve an unbounded number of conductors without
loss. Two deterministic fixed-width derivatives are used here:

- a 544-coordinate permutation-invariant layout view for maps and retrieval;
- a 480-coordinate graph-native reciprocal pair-query view for diagnosis;
- a 432-coordinate production pair view that combines the proven 240-coordinate
  v3 fixed-stack core with 192 coordinates of all-other-conductor context.

Passing this notebook does **not** mean that a fast 2-D proxy has become a 3-D
field solver. It means that the representation behaves sensibly under the
planar tests we can currently perform, while leaving the missing high-fidelity
tests visible.
"""),
    code(r"""
from pathlib import Path
import json, os, subprocess, sys

REPO = Path.cwd().resolve()
if not (REPO / "squadds").is_dir():
    REPO = REPO.parent
sys.path.insert(0, str(REPO))

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots
from scipy.stats import spearmanr

from squadds.layouts.geometry_v2 import read_layer_geometry
from squadds.layouts.geometry_v3 import V3_BLOCK_SLICES
from squadds.layouts.geometry_v4 import encode_v4_graph, layout_view_v4, pair_view_v4

pd.set_option("display.max_columns", 40)
pio.renderers.default = "notebook"
SEED = 24
RUNTIME = REPO / "tutorials/runtime/tutorial24"
SCORECARD_PATH = RUNTIME / "acceptance_scorecard.csv"
SWEEP_PATH = RUNTIME / "supplied-sweep-sample.parquet"
V4_BALANCED_PATH = RUNTIME / "planar-terminal-graph-v4-balanced.parquet"
V3_BALANCED_PATH = REPO / "tutorials/runtime/tutorial23/capacitance-operator-v3-balanced.parquet"
V2_BALANCED_PATH = Path(os.getenv("SQUADDS_V2_ALL_TABLE", Path.home()/".cache/squadds/tutorial20/universal-geometry-v2-portcomplete.parquet"))
ATLAS_PATH = RUNTIME / "qmetal-atlas/manifest.json"
MODULAR_PATH = RUNTIME / "modularity/summary.json"
PREDICTIVE_DIR = RUNTIME / "predictive"
FIGURE_DIR = REPO.parent / "embedding-transfer-paper/figures/generated"

if not SCORECARD_PATH.is_file():
    subprocess.run([sys.executable, str(REPO/"scripts/run_embedding_acceptance.py")], check=True, cwd=REPO)
if not SWEEP_PATH.is_file():
    subprocess.run([sys.executable, str(REPO/"scripts/build_tutorial24_sweep_sample.py")], check=True, cwd=REPO)
if not V4_BALANCED_PATH.is_file() and V3_BALANCED_PATH.is_file():
    subprocess.run([sys.executable, str(REPO/"scripts/build_v4_balanced_table.py")], check=True, cwd=REPO)
if not MODULAR_PATH.is_file():
    subprocess.run([sys.executable, str(REPO/"scripts/run_tutorial24_modular_studies.py")], check=True, cwd=REPO)
if not (PREDICTIVE_DIR/"manifest.json").is_file():
    subprocess.run([sys.executable, str(REPO/"scripts/run_tutorial24_predictive_studies.py")], check=True, cwd=REPO)

scorecard = pd.read_csv(SCORECARD_PATH)
controlled = pd.read_csv(RUNTIME/"controlled_manifest.csv")
trajectories = pd.read_csv(RUNTIME/"physical_trajectories.csv")
sweeps = pd.read_parquet(SWEEP_PATH)
embeddings = np.load(RUNTIME/"controlled_embeddings.npz")
print(f"Controlled GDS: {len(controlled)} | supplied sweep sample: {len(sweeps)}")
print("Source campaigns:", ", ".join(sorted(sweeps.campaign.unique())))

def repo_path(value):
    path=Path(value)
    return path if path.is_absolute() else REPO/path
"""),
    md(r"""
## First, a mental model of the representation

A native parameter such as `finger_length` is meaningful for an IDC but has no
obvious counterpart on a transmon cross or a concentric capacitor. GDS gives us
a shared physical language: metal islands, the surrounding ground, and markers
that say which island is a terminal. v4 turns that picture into a conductor
graph. Nodes describe individual metal islands; edges describe how pairs face,
separate, and screen one another; global features describe the device as a
whole.

![Mermaid diagram of the v4 representation anatomy](assets/tutorial24/representation_anatomy.svg)

*[Mermaid source](assets/tutorial24/representation_anatomy.mmd).*

### Planar paper-figure checklist

Nothing from the feasible planar figure set is hidden behind a future-work
sentence. Each publication panel below is regenerated by this notebook's final
cell and saved in `embedding-transfer-paper/figures/generated/`.

| publication panel | interactive evidence here |
| --- | --- |
| `acceptance_scorecard.png` | Section 1 |
| `physical_trajectories.png` | Section 3 |
| `block_ablation.png` | Section 5 |
| `qmetal_atlas.png` | Sections 6–7, including the A/B geometry browser |
| `modular_arithmetic.png` | Section 8 |
| `native_vs_embedding.png` | Section 9 |
| `similarity_capacitance.png` | Section 10 |
| `transfer_learning.png` | Section 11 |
| `generalist_growth.png` | Section 12 |
| `unseen_composite.png` | Section 13 |

The separate manuscript also contains two native TikZ schematics for data
fragmentation and the arbitrary-terminal representation contract. The only
omitted requested class is flip-chip. High-fidelity composite prediction is
shown as *not tested* rather than replaced with the available 2-D proxy.

The Sankey diagram below is a map of the evidence, not a numerical result. Its
links show which downstream questions consume the same frozen geometry object;
their widths do not represent sample count.
"""),
    code(r"""
labels=["IDC parameters","Transmon parameters","Concentric/star parameters","GDS + semantic sidecar",
        "v4 conductor graph","acceptance gates","capacitance audit","similarity calibration",
        "few-shot transfer","generalist growth","unseen composition"]
sources=[0,1,2,3,4,4,4,4,4,4]
targets=[3,3,3,4,5,6,7,8,9,10]
values=[1,1,1,3,1,1,1,1,1,1]
fig=go.Figure(go.Sankey(
    arrangement="snap",node=dict(label=labels,pad=18,thickness=18,color=["#7aa6c2"]*3+["#ef9f76","#3b7d6b"]+["#b8c4d6"]*6),
    link=dict(source=sources,target=targets,value=values,color="rgba(71,103,145,.28)")))
fig.update_layout(title="One physical interface, multiple falsifiable evaluations",height=460,font_size=12)
fig.show()
"""),
    md(r"""
## 1. Decide what “physically sensible” means before scoring an encoder

If thresholds are chosen after seeing the curves, almost any embedding can be
made to look successful. We therefore freeze the tolerances first. The first
five tests are *negative controls*: translation, rotation, reflection, and the
arbitrary size of the outer ground crop should not move the vector. The next
three are *positive controls*: a scale, local gap, facing-length, or moat change
must move it smoothly and in the correct order. The final test asks whether the
data structure can grow beyond a hard-coded terminal count.

v0/v1 are left out because their fitted catalogue normalization changes when a
new batch is written. v2 is the earliest catalogue-independent reference.

| Requirement | Gate |
| --- | --- |
| Repeatability | bitwise equality |
| Translation | relative drift ≤ `1e-7` |
| Right-angle rotation / reflection | drift ≤ `5e-4` |
| Arbitrary rotation | drift ≤ `3e-3` |
| Outer ground crop | drift ≤ `1e-5` |
| Physical sensitivity | median physical drift ≥ `10×` nuisance drift |
| Sweep continuity | largest step ≤ `5×` median adjacent step |
| Gap ordering | absolute Spearman correlation ≥ `0.95` |
| Arbitrary terminals | no terminal cap; every other conductor enters the pair context |

> **How to read the scorecard:** a green cell means the frozen threshold was
> met. It does not mean that representation is universally “better.” The
> sensitivity ratio can also become enormous when nuisance drift is nearly
> zero, so always inspect the absolute trajectories in Section 3.
"""),
    code(r"""
gate_columns = [c for c in scorecard if c.startswith("pass_")]
gate_labels = [c.replace("pass_", "").replace("_", " ") for c in gate_columns]
z = scorecard[gate_columns].astype(int).to_numpy()
fig = go.Figure(go.Heatmap(
    z=z, x=gate_labels, y=scorecard.representation,
    text=np.where(z == 1, "PASS", "FAIL"), texttemplate="%{text}",
    colorscale=[[0,"#D1495B"],[0.499,"#D1495B"],[0.5,"#2A9D8F"],[1,"#2A9D8F"]],
    showscale=False, hovertemplate="%{y}<br>%{x}: %{text}<extra></extra>"))
fig.update_layout(title="Predeclared planar representation gates", height=430,
                  xaxis_title="acceptance requirement", yaxis_title="representation")
fig.show()
display(scorecard[["representation","dimensions","numerical_gates_passed","numerical_gates_total",
                   "arbitrary_terminal_contract","distinct_control_vectors","total_control_vectors"]])
"""),
    md(r"""
### What the scorecard says physically

v2 still remembers the drawing frame: a 37° rotation changes the vector enough
to fail the rotation gate. v3 removes that coordinate dependence for a selected
two-terminal problem, but it has no place to put a third, fourth, or twelfth
conductor. v4 keeps v3's pose robustness while changing the object from a fixed
terminal vector into a graph with one node per conductor. That is why v3 can
pass 9/9 numerical tests and still fail the scientific scope test.
"""),
    md(r"""
## 2. Build the equivalent of a calibration wafer in GDS

Before using thousands of historical designs, we make deliberately simple
devices whose physical change is known. Blue shapes are isolated signal-metal
islands. The pale region is ground, with the device clearance cut out as a true
hole. Orange/purple markers bridge each signal island to ground and give the
terminal ordering used by the capacitance problem.

The layer contract is `(1,10)` for signal metal, `(1,0)` for ground, and
`(2+i,0)` for terminal `i`. A JSON sidecar names these roles and reserves fields
for a future material/thickness stack. Use the menu to move from the baseline
pair through one-at-a-time physical changes and then to 5- and 12-terminal
controls.
"""),
    code(r"""
def polygon_lines(shape):
    polygons = [p for p in getattr(shape, "geoms", [shape]) if p.geom_type == "Polygon"]
    lines=[]
    for polygon in polygons:
        lines.append(np.asarray(polygon.exterior.coords))
        lines.extend(np.asarray(ring.coords) for ring in polygon.interiors)
    return lines

examples = ["pair_baseline","pair_gap_14p0","pair_facing_90p0","pair_ground_gap_14p0","radial_5_terminal","radial_12_terminal"]
traces=[]
for fixture in examples:
    path=repo_path(controlled.set_index("fixture_name").loc[fixture,"gds_path"])
    geometry=read_layer_geometry(path)
    local=[]
    for key, shape in sorted(geometry.items()):
        role="ground" if key==(1,0) else "conductor" if key==(1,10) else "port"
        for line_index,line in enumerate(polygon_lines(shape)):
            local.append(go.Scatter(x=line[:,0],y=line[:,1],mode="lines",
                fill="toself" if role!="ground" and line_index==0 else None,
                name=f"{role} {key}",legendgroup=f"{fixture}-{role}",
                line=dict(width=1 if role=="ground" else 2),
                visible=(fixture==examples[0]),hovertemplate=f"{fixture}<br>{role} {key}<extra></extra>"))
    traces.extend(local)
buttons=[]; offset=0
for fixture in examples:
    count=0
    geometry=read_layer_geometry(repo_path(controlled.set_index("fixture_name").loc[fixture,"gds_path"]))
    for shape in geometry.values(): count += len(polygon_lines(shape))
    visible=[False]*len(traces)
    for i in range(offset,offset+count): visible[i]=True
    buttons.append(dict(label=fixture,method="update",args=[{"visible":visible},{"title":"Standardized GDS — "+fixture}]))
    offset += count
fig=go.Figure(traces)
fig.update_layout(title="Standardized GDS — "+examples[0],height=570,
    xaxis=dict(title="x (µm)",scaleanchor="y",scaleratio=1),yaxis_title="y (µm)",
    updatemenus=[dict(buttons=buttons,direction="down",x=1,xanchor="right")])
fig.show()
"""),
    md(r"""
## 3. Can the representation separate coordinate choices from electrostatics?

There are two experiments here.

- In the **nuisance experiment**, the metal/ground relationship is unchanged;
  only the coordinate frame or distant crop moves. Every bar should be tiny.
- In the **physical experiment**, one geometric control changes while all
  others stay fixed. Each curve should leave zero smoothly as we move away from
  the baseline.

These distances use the full frozen vectors—no PCA and no learned metric. On
the log-scale nuisance plot, lower is better. On the four trajectory panels,
the central zero is the baseline and a smooth rise is the desired response.
"""),
    code(r"""
nuisance_columns=["translation_drift","rotation_90_drift","rotation_37_drift","reflection_drift","outer_crop_max_drift"]
fig=go.Figure()
for _,row in scorecard.iterrows():
    fig.add_trace(go.Bar(name=row.representation,x=[c.replace("_drift","").replace("_"," ") for c in nuisance_columns],
                         y=[max(float(row[c]),1e-12) for c in nuisance_columns],
                         hovertemplate="%{x}<br>relative drift=%{y:.3e}<extra>"+row.representation+"</extra>"))
fig.update_layout(title="Pose and crop leakage",barmode="group",height=470,yaxis_type="log",
                  yaxis_title="relative embedding drift",xaxis_title="nuisance transformation")
fig.show()
"""),
    code(r"""
groups=list(trajectories.group.unique())
fig=make_subplots(rows=2,cols=2,subplot_titles=[g.replace("_"," ") for g in groups])
for representation in scorecard.representation:
    for gi,group in enumerate(groups):
        d=trajectories[(trajectories.representation==representation)&(trajectories.group==group)].sort_values("control_value")
        fig.add_trace(go.Scatter(x=d.control_value,y=d.distance_from_baseline,mode="lines+markers",
            name=representation,legendgroup=representation,showlegend=(gi==0),
            hovertemplate="control=%{x:g}<br>relative drift=%{y:.3e}<extra>"+representation+"</extra>"),
            row=gi//2+1,col=gi%2+1)
for gi in range(len(groups)):
    fig.update_xaxes(title=groups[gi].replace("_"," "),row=gi//2+1,col=gi%2+1)
    fig.update_yaxes(title="distance from baseline",row=gi//2+1,col=gi%2+1)
fig.update_layout(title="Physical perturbation trajectories",height=720)
fig.show()
"""),
    md(r"""
## 4. Why a capacitance problem is naturally a graph

An `N`-conductor electrostatic problem has `N` conductor objects and pairwise
relationships between them. Padding a vector to “at most four ports” hides that
physics and eventually fails. In v4, every disconnected signal island becomes
a node, every unordered pair gets a symmetric edge, and ground participates in
the low-fidelity operator.

The heatmap below is the pair-gap channel for a 12-terminal control. Hover any
cell to inspect a conductor pair. A conductor without a marker is not discarded;
it remains a physical node whose semantic name is unresolved until a net or
simulation sidecar supplies it. The pooled layout view is for maps/retrieval;
capacitance models use pair queries that retain the influence of all other
conductors.
"""),
    code(r"""
radial_path=repo_path(controlled.set_index("fixture_name").loc["radial_12_terminal","gds_path"])
radial_graph=encode_v4_graph(radial_path,layer_contract=radial_path.with_suffix(".layers.json"))
gap_matrix=np.expm1(radial_graph.edge_features[:,:,2])
fig=go.Figure(go.Heatmap(z=gap_matrix,x=radial_graph.node_ids,y=radial_graph.node_ids,
    colorbar=dict(title="µm"),hovertemplate="%{y} ↔ %{x}<br>gap=%{z:.3f} µm<extra></extra>"))
fig.update_layout(title=f"v4 symmetric conductor graph: {len(radial_graph.node_ids)} nodes, no padding cap",
                  height=560,xaxis_title="conductor node",yaxis_title="conductor node")
fig.show()
print("node tensor",radial_graph.node_features.shape,"edge tensor",radial_graph.edge_features.shape,
      "proxy matrix",radial_graph.proxy_matrix_fF.shape)
"""),
    md(r"""
## 5. Open the vector and ask which physical channel is doing the work

A single norm can hide a bad coordinate inside a large vector. We therefore
score interpretable blocks separately. In device language:

| block | physical content |
| --- | --- |
| global | device scale, area/perimeter summaries, topology counts |
| node statistics | distribution of individual conductor shapes |
| edge statistics | gaps, facing lengths, and pairwise screening summaries |
| selected pair | the two conductors whose mutual capacitance is requested |
| other-conductor context | how every third body perturbs that selected pair |

On the first plot, the ideal region is **upper left**: strong motion under a
physical control and little motion under pose/crop. The cumulative/drop-one
plot asks whether the conclusion depends on only one block. The environment
block is omitted because all current layouts share one stack; adding a constant
stack/device ratio would mainly leak family identity.
"""),
    code(r"""
base=int(controlled.index[controlled.fixture_name=="pair_baseline"][0])
nuisance_idx=controlled.index[controlled.fixture_name.isin(["pair_translated","pair_rotated_90","pair_rotated_37","pair_reflected","pair_ground_crop_small","pair_ground_crop_large"])].tolist()
physical_idx=controlled.index[controlled.perturbation_group.isin(["uniform_scale","terminal_gap_um","facing_length_um","ground_clearance_um"])].tolist()
block_specs={
 "v2":{"metrics":slice(0,48),"coupling":slice(48,264),"shape":slice(264,392),"parameters":slice(392,488),"physics":slice(488,536)},
 "v3_core":{"metrics":V3_BLOCK_SLICES["metrics"],"interactions":V3_BLOCK_SLICES["interactions"],"operator":V3_BLOCK_SLICES["operator"],"topology":V3_BLOCK_SLICES["topology"],"electrostatic":V3_BLOCK_SLICES["electrostatic"]},
 "v4_graph_pair":{"global":slice(0,64),"endpoint_sum":slice(64,128),"endpoint_difference":slice(128,192),"selected_edge":slice(192,288),"other_conductor_context":slice(288,480)},
 "v4_hybrid_pair":{"v3_pair_core":slice(0,240),"all_other_context":slice(240,432)},
 "v4_layout":{"global":slice(0,64),"node_mean":slice(64,128),"node_std":slice(128,192),"node_max":slice(192,256),"edge_mean":slice(256,352),"edge_std":slice(352,448),"edge_max":slice(448,544)},
}
rows=[]
for rep,blocks in block_specs.items():
    X=embeddings[rep]
    for block,s in blocks.items():
        ref=X[base,s]; norm=max(np.linalg.norm(ref),1e-12)
        nuisance=max(np.linalg.norm(X[i,s]-ref)/norm for i in nuisance_idx)
        physical=np.median([np.linalg.norm(X[i,s]-ref)/norm for i in physical_idx])
        rows.append({"representation":rep.replace("_"," "),"block":block,"nuisance":nuisance,"physical":physical,
                     "ratio":physical/max(nuisance,1e-12)})
block_audit=pd.DataFrame(rows)
fig=go.Figure()
for rep,d in block_audit.groupby("representation"):
    fig.add_trace(go.Scatter(x=np.maximum(d.nuisance,1e-12),y=np.maximum(d.physical,1e-12),mode="markers+text",
        text=d.block,textposition="top center",name=rep,customdata=d.ratio,
        hovertemplate="%{text}<br>nuisance=%{x:.2e}<br>physical=%{y:.2e}<br>ratio=%{customdata:.1f}<extra>"+rep+"</extra>"))
fig.update_layout(title="Block audit: physical response versus pose leakage",height=560,
                  xaxis=dict(title="maximum nuisance drift",type="log"),
                  yaxis=dict(title="median physical drift",type="log"))
fig.show()
display(block_audit.sort_values(["representation","ratio"]))

layout_blocks=block_specs["v4_layout"]
ordered_blocks=list(layout_blocks)
ablation=[]
def score_subset(indices):
    X=embeddings["v4_layout"][:,indices];ref=X[base];norm=max(np.linalg.norm(ref),1e-12)
    nuisance=max(np.linalg.norm(X[i]-ref)/norm for i in nuisance_idx)
    physical=np.median([np.linalg.norm(X[i]-ref)/norm for i in physical_idx])
    return nuisance,physical,physical/max(nuisance,1e-12)
for count in range(1,len(ordered_blocks)+1):
    names=ordered_blocks[:count]
    indices=np.concatenate([np.arange(layout_blocks[name].start,layout_blocks[name].stop) for name in names])
    nuisance,physical,ratio=score_subset(indices)
    ablation.append({"mode":"cumulative","selection":" + ".join(names),"dimensions":len(indices),
                     "nuisance":nuisance,"physical":physical,"ratio":ratio})
for omitted in ordered_blocks:
    names=[name for name in ordered_blocks if name!=omitted]
    indices=np.concatenate([np.arange(layout_blocks[name].start,layout_blocks[name].stop) for name in names])
    nuisance,physical,ratio=score_subset(indices)
    ablation.append({"mode":"drop one","selection":"without "+omitted,"dimensions":len(indices),
                     "nuisance":nuisance,"physical":physical,"ratio":ratio})
block_ablation=pd.DataFrame(ablation)
block_ablation.to_csv(RUNTIME/"block_ablation.csv",index=False)
fig=make_subplots(rows=1,cols=2,subplot_titles=("Cumulative v4 blocks","Drop-one v4 blocks"))
for column,mode in enumerate(["cumulative","drop one"],start=1):
    d=block_ablation[block_ablation["mode"]==mode]
    fig.add_trace(go.Bar(y=d.selection,x=d.ratio,orientation="h",customdata=np.c_[d.nuisance,d.physical,d.dimensions],
        hovertemplate="%{y}<br>physical/nuisance=%{x:.2e}<br>nuisance=%{customdata[0]:.2e}<br>physical=%{customdata[1]:.2e}<br>dims=%{customdata[2]:.0f}<extra></extra>"),row=1,col=column)
    fig.update_xaxes(type="log",title="physical / nuisance response",row=1,col=column)
fig.update_layout(title="v4 layout-view cumulative and drop-one block ablation",height=650,showlegend=False)
fig.show()
"""),
    md(r"""
## 6. Leave the calibration wafer and look at real swept layouts

The controlled shapes tell us whether the instrument behaves properly; they do
not tell us whether it has enough resolution for real designs. The supplied
folder contains 39,070 GDS/JSON pairs across six campaigns. To keep this live
notebook responsive, we take a deterministic sample of 24 from each: four IDC
regimes plus the new concentric and star families.

First inspect the table: it shows how many conductor islands and marked or
unmarked terminals the parser actually found. Then use the representation menu
on the atlas. PCA is used only to draw two coordinates on screen; all collision
counts are computed from the complete vectors. Of particular interest, the
star contains two physical conductor islands but only one marker. v4 keeps the
unmarked island rather than erasing a screening body from the physics.
"""),
    code(r"""
summary=sweeps.groupby("family").agg(rows=("source_id","size"),unique_gds=("layout_sha256","nunique"),
    terminals=("terminal_count_v4","median"),unmarked=("unmarked_conductor_count_v4","max"),
    median_area_um2=("conductor_area_um2","median"))
display(summary.round(2))
for column in ["embedding_v2","embedding_v2_conditioned","embedding_v3_core","embedding_v3_complete","embedding_v4_layout"]:
    unique=sweeps[column].map(lambda value: np.asarray(value,dtype=np.float32).tobytes()).nunique()
    print(f"{column}: {unique}/{len(sweeps)} distinct sampled vectors")
"""),
    code(r"""
def pca2(values):
    X=np.vstack(values).astype(float)
    mean=X.mean(axis=0); scale=X.std(axis=0); scale=np.where(scale>1e-9,scale,1)
    Z=np.clip((X-mean)/scale,-10,10)
    _,_,vh=np.linalg.svd(Z,full_matrices=False)
    return Z@vh[:2].T

representations={
    "v2":pca2(sweeps.embedding_v2),
    "v2 conditioned":pca2(sweeps.embedding_v2_conditioned),
    "v3 core":pca2(sweeps.embedding_v3_core),
    "v4 layout":pca2(sweeps.embedding_v4_layout),
}
traces=[]
families=list(sweeps.family.unique())
for rep,coords in representations.items():
    for family in families:
        mask=(sweeps.family==family).to_numpy()
        traces.append(go.Scatter(x=coords[mask,0],y=coords[mask,1],mode="markers",name=family,
            legendgroup=family,visible=(rep=="v2"),marker=dict(size=7,opacity=.75),
            customdata=sweeps.loc[mask,["campaign","source_id","terminal_count_v4"]],
            hovertemplate="%{customdata[0]} / %{customdata[1]}<br>terminals=%{customdata[2]}<br>PC1=%{x:.2f}<br>PC2=%{y:.2f}<extra>"+family+"</extra>"))
buttons=[]
for ri,rep in enumerate(representations):
    visible=[False]*len(traces)
    for i in range(len(families)): visible[ri*len(families)+i]=True
    buttons.append(dict(label=rep,method="update",args=[{"visible":visible},{"title":"Supplied sweep atlas — "+rep}]))
fig=go.Figure(traces)
fig.update_layout(title="Supplied sweep atlas — v2",height=620,xaxis_title="visualization PC1",yaxis_title="visualization PC2",
                  updatemenus=[dict(buttons=buttons,direction="down",x=1,xanchor="right")])
fig.show()
"""),
    code(r"""
separation=[]
for rep,coords in representations.items():
    for family in families:
        mask=(sweeps.family==family).to_numpy(); centre=coords[mask].mean(axis=0)
        within=np.mean(np.linalg.norm(coords[mask]-centre,axis=1))
        other=[]
        for second in families:
            if second==family: continue
            other.append(np.linalg.norm(centre-coords[(sweeps.family==second).to_numpy()].mean(axis=0)))
        separation.append({"representation":rep,"family":family,"within_radius":within,
                           "nearest_family_centroid":min(other),"separation_ratio":min(other)/max(within,1e-12)})
display(pd.DataFrame(separation).pivot(index="family",columns="representation",values="separation_ratio").round(2))
"""),
    md(r"""
### What “unique vector” does and does not mean

All 144 sampled physical layouts produce distinct complete vectors. That is a
useful empirical collision check, not a proof that no two imaginable GDS files
can collide. The converse matters too: two Qiskit Metal classes with identical
metal geometry *should* coincide. Separating them only because their Python
class names differ would inject labels the electrostatics cannot see.
"""),
    md(r"""
## 7. A visual dictionary of Qiskit Metal components

This atlas answers a practical question: *when two points are close in the
embedding, what do the corresponding devices actually look like?* We instantiate
every production `QComponent` that can be generated from the frozen local
Qiskit Metal checkout. Routes use the same endpoint fixture, and helper
launchpads are excluded from the component-owned geometry.

Hover a PCA point to preview it as device B; click to pin it. Select any device
as reference A, use **Same physical scale** when comparing dimensions, and swap
A/B when useful. The panel reports complete-vector distance and whether two
class names are literally the same physical-geometry equivalence class. Empty
semantic/context-only components remain in the manifest instead of being
quietly omitted.
"""),
    code(r"""
if ATLAS_PATH.is_file():
    from IPython.display import HTML

    def svg_paths(shape):
        paths=[]
        for polygon in getattr(shape,"geoms",[shape]):
            if polygon.geom_type!="Polygon" or polygon.is_empty:
                continue
            rings=[polygon.exterior,*polygon.interiors]
            commands=[]
            for ring in rings:
                coordinates=np.asarray(ring.coords,dtype=float)
                commands.append("M "+" L ".join(f"{x:.4f} {-y:.4f}" for x,y in coordinates)+" Z")
            paths.append(" ".join(commands))
        return paths

    atlas_payload=json.loads(ATLAS_PATH.read_text())
    atlas_rows=[]
    for record in atlas_payload["records"]:
        component=record["component"]
        item={"class_name":component["class_name"],"category":component["category"],
              "status":record["status"],"geometry_hash":record.get("geometry_id"),
              "terminal_count":record.get("terminal_count"),"embedding_v4_layout":None}
        if record["status"]=="generated_valid":
            gds_path=ATLAS_PATH.parent/record["gds_path"]
            graph=encode_v4_graph(
                gds_path,
                layer_contract=ATLAS_PATH.parent/record["layer_contract_path"],
            )
            item["embedding_v4_layout"]=layout_view_v4(graph)
            geometry=read_layer_geometry(gds_path)
            conductor=geometry[(1,10)]
            full_bounds=np.asarray([shape.bounds for shape in geometry.values()],dtype=float)
            left,bottom=np.min(full_bounds[:,:2],axis=0);right,top=np.max(full_bounds[:,2:],axis=0)
            cl,cb,cr,ct=conductor.bounds
            drawing=[]
            for key,shape in sorted(geometry.items()):
                role="ground" if key==(1,0) else "conductor" if key==(1,10) else "port"
                drawing.extend({"role":role,"d":path} for path in svg_paths(shape))
            item.update({
                "drawing":drawing,
                "svg_bounds":[float(left),float(-top),float(right),float(-bottom)],
                "conductor_width_um":float(cr-cl),"conductor_height_um":float(ct-cb),
                "conductor_islands":int(record["conductor_island_count"]),
                "unmarked_conductors":int(graph.metadata["unmarked_conductor_count"]),
            })
        atlas_rows.append(item)
    atlas=pd.DataFrame(atlas_rows)
    display(atlas.groupby("status").size().rename("components").to_frame())
    eligible=atlas[atlas.embedding_v4_layout.notna()].copy() if "embedding_v4_layout" in atlas else atlas.iloc[0:0]
    if len(eligible):
        coords=pca2(eligible.embedding_v4_layout)
        vectors=np.vstack(eligible.embedding_v4_layout).astype(float)
        norms=np.linalg.norm(vectors,axis=1)
        relative=np.linalg.norm(vectors[:,None,:]-vectors[None,:,:],axis=2)/np.maximum(norms[:,None],1e-12)
        cosine=(vectors@vectors.T)/np.maximum(norms[:,None]*norms[None,:],1e-12)
        groups={member:group["members"] for group in atlas_payload["geometry_equivalence_classes"] for member in group["members"]}
        browser=[]
        for position,(_,row) in enumerate(eligible.iterrows()):
            browser.append({
                "name":row.class_name,"category":row.category,"geometry":row.geometry_hash,
                "equivalents":groups[row.class_name],"terminals":int(row.terminal_count),
                "islands":int(row.conductor_islands),"unmarked":int(row.unmarked_conductors),
                "width":round(float(row.conductor_width_um),3),"height":round(float(row.conductor_height_um),3),
                "x":round(float(coords[position,0]),6),"y":round(float(coords[position,1]),6),
                "bounds":row.svg_bounds,"paths":row.drawing,
            })
        payload=json.dumps({"items":browser,"relative":relative.round(6).tolist(),"cosine":cosine.round(6).tolist()}).replace("</","<\\/")
        atlas_html=r'''
<section id="qmetal-atlas-browser" class="qma-root">
  <style>
    #qmetal-atlas-browser{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033}
    #qmetal-atlas-browser .qma-help{margin:0 0 10px;color:#526079;font-size:13px}
    #qmetal-atlas-browser .qma-controls{display:grid;grid-template-columns:minmax(190px,1fr) minmax(190px,1fr) auto auto;gap:10px;align-items:end;margin:8px 0 12px}
    #qmetal-atlas-browser label{display:grid;gap:4px;color:#526079;font-size:12px;font-weight:600}
    #qmetal-atlas-browser select,#qmetal-atlas-browser button{height:34px;border:1px solid #c9d2df;background:#fff;color:#172033;border-radius:6px;padding:0 9px;font:inherit}
    #qmetal-atlas-browser button{cursor:pointer;font-weight:600}
    #qmetal-atlas-browser .qma-checks{display:flex;gap:14px;align-items:center;height:34px;white-space:nowrap}
    #qmetal-atlas-browser .qma-checks label{display:flex;align-items:center;gap:6px;font-weight:500}
    #qmetal-atlas-browser .qma-layout{display:grid;grid-template-columns:minmax(420px,1.25fr) minmax(390px,1fr);gap:16px;align-items:start}
    #qmetal-atlas-browser .qma-plot{height:610px;border:1px solid #dbe2ea;border-radius:8px;overflow:hidden}
    #qmetal-atlas-browser .qma-distance{min-height:38px;padding:8px 10px;border:1px solid #dbe2ea;border-radius:7px;background:#f7f9fc;font-size:13px;line-height:1.45}
    #qmetal-atlas-browser .qma-panels{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}
    #qmetal-atlas-browser .qma-card{border:1px solid #dbe2ea;border-radius:8px;background:#fff;overflow:hidden}
    #qmetal-atlas-browser .qma-title{padding:9px 10px 3px;font-weight:700;font-size:14px;overflow-wrap:anywhere}
    #qmetal-atlas-browser .qma-meta{padding:0 10px 8px;color:#526079;font-size:11px;line-height:1.45;min-height:52px}
    #qmetal-atlas-browser .qma-svg{display:block;width:100%;height:350px;background:#fbfcfe;border-top:1px solid #edf1f5}
    #qmetal-atlas-browser .qma-ground{fill:#e8edf3;stroke:#97a5b6;stroke-width:.6;fill-rule:evenodd}
    #qmetal-atlas-browser .qma-conductor{fill:#27689d;stroke:#174a72;stroke-width:.8;fill-rule:evenodd}
    #qmetal-atlas-browser .qma-port{fill:#ee6a3b;stroke:#a83d1e;stroke-width:.7;fill-rule:evenodd}
    #qmetal-atlas-browser path{vector-effect:non-scaling-stroke}
    @media(max-width:980px){#qmetal-atlas-browser .qma-layout{grid-template-columns:1fr}#qmetal-atlas-browser .qma-plot{height:500px}}
    @media(max-width:680px){#qmetal-atlas-browser .qma-controls{grid-template-columns:1fr}#qmetal-atlas-browser .qma-panels{grid-template-columns:1fr}#qmetal-atlas-browser .qma-svg{height:300px}}
  </style>
  <p class="qma-help">Hover a point to preview B. Click a point to pin B. Choose any coincident component from the selectors; equal physical layouts intentionally overlap.</p>
  <div class="qma-controls">
    <label>Reference A<select data-ref></select></label>
    <label>Candidate B<select data-candidate></select></label>
    <button type="button" data-swap>Swap A / B</button>
    <div class="qma-checks">
      <label><input type="checkbox" data-lock> Keep B fixed</label>
      <label><input type="checkbox" data-scale> Same physical scale</label>
    </div>
  </div>
  <div class="qma-layout">
    <div class="qma-plot" data-plot aria-label="PCA map of Qiskit Metal component embeddings"></div>
    <div>
      <div class="qma-distance" data-distance></div>
      <div class="qma-panels">
        <article class="qma-card"><div class="qma-title" data-title-a></div><div class="qma-meta" data-meta-a></div><svg class="qma-svg" data-svg-a role="img"></svg></article>
        <article class="qma-card"><div class="qma-title" data-title-b></div><div class="qma-meta" data-meta-b></div><svg class="qma-svg" data-svg-b role="img"></svg></article>
      </div>
    </div>
  </div>
  <script>
  (()=>{
    const root=document.getElementById("qmetal-atlas-browser");
    const payload=__ATLAS_PAYLOAD__;
    const items=payload.items, relative=payload.relative, cosine=payload.cosine;
    const byName=(name)=>Math.max(0,items.findIndex(d=>d.name===name));
    let a=byName("TransmonCross"),b=byName("CapNInterdigitalTee"),locked=false,shared=false;
    const ref=root.querySelector("[data-ref]"),candidate=root.querySelector("[data-candidate]");
    items.forEach((item,index)=>{
      for(const select of [ref,candidate]){const option=document.createElement("option");option.value=index;option.textContent=`${item.category} · ${item.name}`;select.appendChild(option)}
    });
    const squareBounds=(item,extent)=>{const [l,t,r,bot]=item.bounds,cx=(l+r)/2,cy=(t+bot)/2;return [cx-extent/2,cy-extent/2,extent,extent]};
    const ownExtent=item=>Math.max(item.bounds[2]-item.bounds[0],item.bounds[3]-item.bounds[1])*1.08;
    const draw=(slot,index,extent)=>{
      const item=items[index],svg=root.querySelector(`[data-svg-${slot}]`),bounds=squareBounds(item,extent||ownExtent(item));
      svg.setAttribute("viewBox",bounds.join(" "));svg.setAttribute("aria-label",`${item.name} GDS geometry`);
      svg.innerHTML=item.paths.map(path=>`<path class="qma-${path.role}" d="${path.d}"></path>`).join("");
      root.querySelector(`[data-title-${slot}]`).textContent=`${slot.toUpperCase()} · ${item.name}`;
      const equivalents=item.equivalents.length>1?` · equivalent defaults: ${item.equivalents.join(", ")}`:"";
      root.querySelector(`[data-meta-${slot}]`).textContent=`${item.category} · ${item.terminals} terminal nodes (${item.unmarked} unmarked) · ${item.islands} conductor islands · ${item.width} × ${item.height} µm${equivalents}`;
    };
    const update=()=>{
      ref.value=a;candidate.value=b;
      const extent=shared?Math.max(ownExtent(items[a]),ownExtent(items[b])):null;
      draw("a",a,extent);draw("b",b,extent);
      const same=items[a].geometry===items[b].geometry;
      root.querySelector("[data-distance]").innerHTML=`<strong>${same?"Same physical-geometry class":"Different physical geometries"}</strong> · relative v4 distance ${relative[a][b].toFixed(4)} · cosine ${cosine[a][b].toFixed(4)}${shared?" · drawings share one µm scale":" · each drawing fitted independently"}`;
      if(window.Plotly&&root.querySelector("[data-plot]").data){
        const plot=root.querySelector("[data-plot]"),n=plot.data.length;
        Plotly.restyle(plot,{x:[[items[a].x]],y:[[items[a].y]],text:[[items[a].name]]},[n-2]);
        Plotly.restyle(plot,{x:[[items[b].x]],y:[[items[b].y]],text:[[items[b].name]]},[n-1]);
      }
    };
    const initializePlot=()=>{
      if(!window.Plotly){setTimeout(initializePlot,50);return}
      const categories=[...new Set(items.map(d=>d.category))];
      const colors=["#27689d","#d85832","#4a8f54","#8c61a8","#b58b22","#2b8c8c","#8b5e3c"];
      const traces=categories.map((category,index)=>{const rows=items.map((d,i)=>({d,i})).filter(row=>row.d.category===category);return {type:"scatter",mode:"markers",name:category,x:rows.map(r=>r.d.x),y:rows.map(r=>r.d.y),text:rows.map(r=>r.d.name),customdata:rows.map(r=>r.i),marker:{size:9,color:colors[index%colors.length],opacity:.82,line:{color:"#fff",width:1}},hovertemplate:"<b>%{text}</b><br>"+category+"<br>PC1 %{x:.2f}<br>PC2 %{y:.2f}<extra></extra>"}});
      traces.push({type:"scatter",mode:"markers",name:"Reference A",x:[items[a].x],y:[items[a].y],text:[items[a].name],hoverinfo:"text",marker:{size:18,symbol:"circle-open",color:"#111827",line:{width:3}}});
      traces.push({type:"scatter",mode:"markers",name:"Candidate B",x:[items[b].x],y:[items[b].y],text:[items[b].name],hoverinfo:"text",marker:{size:17,symbol:"diamond-open",color:"#ee6a3b",line:{width:3}}});
      const plot=root.querySelector("[data-plot]");
      Plotly.newPlot(plot,traces,{title:{text:"Qiskit Metal singleton atlas",x:.02},height:610,margin:{l:58,r:16,t:55,b:52},hovermode:"closest",legend:{orientation:"h",y:-.16},xaxis:{title:"visualization PC1",zeroline:false},yaxis:{title:"visualization PC2",zeroline:false},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"#fbfcfe"},{responsive:true,displaylogo:false});
      plot.on("plotly_hover",event=>{const index=event.points[0].customdata;if(Number.isInteger(index)&&!locked){b=index;update()}});
      plot.on("plotly_click",event=>{const index=event.points[0].customdata;if(Number.isInteger(index)){b=index;locked=true;root.querySelector("[data-lock]").checked=true;update()}});
      update();
    };
    ref.addEventListener("change",()=>{a=Number(ref.value);update()});
    candidate.addEventListener("change",()=>{b=Number(candidate.value);locked=true;root.querySelector("[data-lock]").checked=true;update()});
    root.querySelector("[data-lock]").addEventListener("change",event=>{locked=event.target.checked});
    root.querySelector("[data-scale]").addEventListener("change",event=>{shared=event.target.checked;update()});
    root.querySelector("[data-swap]").addEventListener("click",()=>{[a,b]=[b,a];update()});
    update();initializePlot();
  })();
  </script>
</section>
'''.replace("__ATLAS_PAYLOAD__",payload)
        display(HTML(atlas_html))
        print(f"{len(eligible)} geometry-bearing components; {eligible.geometry_hash.nunique()} distinct physical layouts")
else:
    print("Atlas generation is optional at notebook build time. Run scripts/build_qmetal_component_atlas.py to populate:",ATLAS_PATH.parent)
"""),
    md(r"""
## 8. Can devices be assembled by adding their embeddings?

Here is the tempting idea: encode two modules separately and add their vectors.
The field problem warns us why that may fail. Both modules include the same
shared conductor and their own global summaries; a simple sum counts both twice.

![Mermaid diagram contrasting raw vector addition with graph composition](assets/tutorial24/composition_logic.svg)

*[Mermaid source](assets/tutorial24/composition_logic.mmd).*

We test it with actual port-complete GDS, not hand-written vectors. Module A
contains left/shared conductors, module B contains shared/right conductors, and
the composed layout merges the shared terminal into one three-conductor device.
The important distinction is between:

1. **raw fixed-vector arithmetic**, which double-counts global summaries and
   the shared node; and
2. **physical graph composition**, which merges matching ports/nets and then
   re-encodes the resulting geometry.

The first is a falsification test. The second is the supported operation.
Subtraction is evaluated separately with a pose-matched physical perturbation:
the gap-change direction should agree before and after rotating both endpoints.
"""),
    code(r"""
modular_manifest=pd.read_csv(RUNTIME/"modularity/manifest.csv")
modular_blocks=pd.read_csv(RUNTIME/"modularity/block_arithmetic.csv")
modular_summary=json.loads(MODULAR_PATH.read_text())
proxy=np.load(RUNTIME/"modularity/proxy_matrices.npz")

draw_fixtures=["module_a","module_b","joined_three_terminal"]
fig=make_subplots(rows=1,cols=3,subplot_titles=("A: left + shared","B: shared + right","A ⊕ B: merged graph"))
role_style={"ground":("#dfe6ee",.65),"conductor":("#27689d",.9),"port":("#ee6a3b",.9)}
for column,fixture in enumerate(draw_fixtures,start=1):
    row=modular_manifest.set_index("fixture").loc[fixture]
    geometry=read_layer_geometry(repo_path(row.gds_path))
    for key,shape in sorted(geometry.items()):
        role="ground" if key==(1,0) else "conductor" if key==(1,10) else "port"
        color,opacity=role_style[role]
        for line in polygon_lines(shape):
            fig.add_trace(go.Scatter(x=line[:,0],y=line[:,1],mode="lines",fill="toself",
                line=dict(color=color,width=1.3),fillcolor=color,opacity=opacity,
                name=role,legendgroup=role,showlegend=(column==1),
                hovertemplate=f"{fixture}<br>{role} {key}<extra></extra>"),row=1,col=column)
    fig.update_xaxes(scaleanchor=f"y{column if column>1 else ''}",scaleratio=1,title="x (µm)",row=1,col=column)
    fig.update_yaxes(title="y (µm)" if column==1 else None,row=1,col=column)
fig.update_layout(title="Port/net composition happens in geometry space",height=470)
fig.show()

display(pd.DataFrame({
    "test":["naive A+B versus joined","pose-matched physical difference","base rotation","wider-gap rotation"],
    "relative_error_or_drift":[modular_summary["naive_vector_addition_relative_error"],
        modular_summary["pose_matched_delta_relative_error"],modular_summary["base_rotation_relative_drift"],
        modular_summary["wider_gap_rotation_relative_drift"]],
    "cosine_when_defined":[modular_summary["naive_vector_addition_cosine"],
        modular_summary["pose_matched_delta_cosine"],np.nan,np.nan],
}).round(6))
"""),
    code(r"""
fig=make_subplots(rows=1,cols=2,subplot_titles=("Why raw A+B fails, block by block","Pose-matched subtraction direction"))
fig.add_trace(go.Bar(y=modular_blocks.block,x=modular_blocks.naive_addition_relative_error,
    orientation="h",customdata=modular_blocks.delta_cosine,
    hovertemplate="%{y}<br>relative A+B error=%{x:.3f}<br>module/join delta cosine=%{customdata:.3f}<extra></extra>"),1,1)
fig.add_trace(go.Bar(x=["unrotated Δ","rotated Δ"],
    y=[1.0,modular_summary["pose_matched_delta_cosine"]],
    customdata=[0.0,modular_summary["pose_matched_delta_relative_error"]],
    hovertemplate="%{x}<br>cosine to unrotated Δ=%{y:.6f}<br>relative direction error=%{customdata:.6f}<extra></extra>"),1,2)
fig.update_xaxes(title="relative error",row=1,col=1)
fig.update_yaxes(title="cosine agreement",range=[0,1.05],row=1,col=2)
fig.update_layout(title="Raw vector algebra is diagnostic; graph composition is physical",height=520,showlegend=False)
fig.show()
"""),
    md(r"""
### What we learn from the modular experiment

Naive addition has high cosine only because most coordinates share the same
large background, yet its relative error is **0.869**. This is a clean rejection
of `embedding(A) + embedding(B)` as a composition law. In contrast, the
pose-matched gap-change vectors agree with cosine **0.99997** and relative error
**0.0091**. Difference vectors can therefore diagnose a controlled physical
change, but the supported construction of a new device remains: merge the
port/net graph, generate the GDS, and re-encode.
"""),
    md(r"""
## 9. Do we lose useful device knowledge by leaving native parameters behind?

A physicist-designed table is hard to beat inside the family it was built for:
IDC finger length, transmon pad size, and claw gap are compact and meaningful.
But those columns cannot be stacked into one cross-family table without an
arbitrary hand-written translation. This experiment asks a fairer question:
under the same design-disjoint 80/20 split and the same model capacity, how much
within-family predictive power does a universal geometry representation retain?

Use the metric menu to move between `R²` in `log(1+C)`, RMS prediction error in
fF, and median absolute error in fF. Bars are five-repeat means; whiskers are
one standard deviation. Lower is better for the two absolute-error panels.
"""),
    code(r"""
family_scores=pd.read_csv(PREDICTIVE_DIR/"family_specific_baselines.csv")
metric_options={"R² in log1p(C)":"r2_log1p","RMSE (fF)":"rmse_fF","Median absolute error (fF)":"medae_fF"}
summary_family=family_scores.groupby(["family","representation"]).agg(
    r2_log1p=("r2_log1p","mean"),r2_sd=("r2_log1p","std"),
    rmse_fF=("rmse_fF","mean"),rmse_sd=("rmse_fF","std"),
    medae_fF=("medae_fF","mean"),medae_sd=("medae_fF","std")).reset_index()
traces=[]
for metric_index,(label,metric) in enumerate(metric_options.items()):
    error_column={"r2_log1p":"r2_sd","rmse_fF":"rmse_sd","medae_fF":"medae_sd"}[metric]
    for representation,d in summary_family.groupby("representation",sort=False):
        traces.append(go.Bar(x=d.family,y=d[metric],name=representation,legendgroup=representation,
            visible=(metric_index==0),error_y=dict(type="data",array=d[error_column],visible=True),
            customdata=np.c_[d[metric],d[error_column]],
            hovertemplate="%{x}<br>mean=%{customdata[0]:.4f}<br>SD=%{customdata[1]:.4f}<extra>"+representation+"</extra>"))
nrep=summary_family.representation.nunique();buttons=[]
for metric_index,(label,metric) in enumerate(metric_options.items()):
    visible=[False]*len(traces)
    for index in range(metric_index*nrep,(metric_index+1)*nrep): visible[index]=True
    buttons.append(dict(label=label,method="update",args=[{"visible":visible},{"title":"Within-family prediction — "+label,"yaxis":{"title":label}}]))
fig=go.Figure(traces)
fig.update_layout(title="Within-family prediction — R² in log1p(C)",height=520,barmode="group",
    yaxis_title="R² in log1p(C)",updatemenus=[dict(buttons=buttons,direction="down",x=1,xanchor="right")])
fig.show()
display(summary_family.round(4))
"""),
    md(r"""
### Physical reading of the native-baseline result

v4 reaches mean within-family log-`R²` of **0.987**, **0.986**, and **0.978**
for Generalized IDC, Tee, and TransmonCross. The native Transmon variables are
slightly stronger on Transmon (`0.981`), and substantially lower in absolute
error there. That is not a failure of a universal interface: it is evidence
that compact family expertise remains valuable and that universal geometry
does not automatically dominate every native coordinate system.
"""),
    md(r"""
## 10. If two layouts are neighbors, should their capacitances be neighbors?

Not necessarily. Capacitance can be dominated by a small local gap even when
the rest of two layouts looks similar. Still, a useful geometry metric should
provide some statistical prior. We sample 12,000 balanced design pairs and ask
whether greater embedding distance tends to mean greater difference in
capacitance after normalizing each family's `log(1+C)` distribution.

The left chart is the overall Spearman rank correlation with 95% intervals from
200 family-stratified design-cluster bootstrap draws. The heatmaps show which
within- or cross-family pairs create that average. This is a label-informed
calibration audit, not part of the deterministic encoder.
"""),
    code(r"""
distance_audit=pd.read_csv(PREDICTIVE_DIR/"distance_capacitance_correlation.csv")
balanced=distance_audit[distance_audit.family_pair=="all_family_balanced"].copy()
fig=go.Figure(go.Bar(x=balanced.representation,y=balanced.spearman,
    error_y=dict(type="data",symmetric=False,array=balanced.ci95_high-balanced.spearman,
                 arrayminus=balanced.spearman-balanced.ci95_low),
    customdata=np.c_[balanced.ci95_low,balanced.ci95_high,balanced.pairs],
    hovertemplate="%{x}<br>Spearman=%{y:.3f}<br>95% CI [%{customdata[0]:.3f}, %{customdata[1]:.3f}]<br>pairs=%{customdata[2]:.0f}<extra></extra>"))
fig.update_layout(title="Embedding distance versus capacitance difference",height=460,
                  yaxis_title="Spearman rank correlation",xaxis_title="representation")
fig.show()

pairwise=distance_audit[distance_audit.family_pair!="all_family_balanced"].copy()
pairwise[["family_a","family_b"]]=pairwise.family_pair.str.split("|",expand=True,regex=False)
family_order=sorted(set(pairwise.family_a)|set(pairwise.family_b))
fig=make_subplots(rows=1,cols=3,subplot_titles=tuple(balanced.representation))
for column,representation in enumerate(balanced.representation,start=1):
    z=np.full((len(family_order),len(family_order)),np.nan)
    d=pairwise[pairwise.representation==representation]
    for _,row in d.iterrows():
        i=family_order.index(row.family_a);j=family_order.index(row.family_b);z[i,j]=z[j,i]=row.spearman
    fig.add_trace(go.Heatmap(z=z,x=family_order,y=family_order,zmin=-.25,zmax=.55,zmid=0,
        colorscale="RdBu",showscale=(column==3),hovertemplate="%{y} / %{x}<br>Spearman=%{z:.3f}<extra></extra>"),1,column)
fig.update_layout(title="Where distance/capacitance alignment comes from",height=510)
fig.show()
display(balanced.round(4))
"""),
    md(r"""
### Physical reading of the similarity result

The balanced correlations rise from **0.082** for v2 to **0.255** for v3 and
**0.251** for v4. The intervals exclude zero, but the effect remains modest.
Thus nearest geometry is a useful prior, not a calibrated promise of nearest
capacitance. A learned, uncertainty-aware task metric on top of the frozen
geometry graph is the next logical discriminator; it should not be baked into
the deterministic representation itself.
"""),
    md(r"""
## 11. Does the shared representation actually save new simulations?

This is the experiment that converts “similar geometry” into an engineering
claim. A target family keeps the same untouched test designs throughout. We
reveal only 1, 5, 10, 50, or 100 target capacitance labels and compare three
ways of using them.

![Mermaid diagram of the leakage-controlled few-shot protocol](assets/tutorial24/learning_protocol.svg)

*[Mermaid source](assets/tutorial24/learning_protocol.mmd).*

The subsets are nested, so the 10-label run contains the same first five labels
as the 5-label run. “Near” and “far” source families are chosen once from v4
centroid distance—not after looking at transfer scores. Use the representation
menu to inspect v2, v3, and v4. A transfer method earns the claim only when it
beats target-only training at the same label count on the same target test set.
"""),
    code(r"""
transfer=pd.read_csv(PREDICTIVE_DIR/"transfer_learning_curves.csv")
transfer_mean=transfer.groupby(["representation","relation","target_labels","method"]).agg(
    r2=("r2_log1p","mean"),r2_sd=("r2_log1p","std"),rmse=("rmse_fF","mean"),rmse_sd=("rmse_fF","std"),
    medae=("medae_fF","mean"),medae_sd=("medae_fF","std")).reset_index()
transfer_reps=list(transfer_mean.representation.unique());metrics=[("r2","R² log1p(C)"),("rmse","RMSE (fF)"),("medae","MedAE (fF)")]
fig=make_subplots(rows=1,cols=3,subplot_titles=tuple(label for _,label in metrics))
trace_rep=[]
for representation in transfer_reps:
    drep=transfer_mean[transfer_mean.representation==representation]
    for column,(metric,label) in enumerate(metrics,start=1):
        for (relation,method),d in drep.groupby(["relation","method"],sort=False):
            d=d.sort_values("target_labels")
            fig.add_trace(go.Scatter(x=d.target_labels,y=d[metric],mode="lines+markers",
                name=f"{relation} · {method.replace('_',' ')}",legendgroup=f"{relation}-{method}",
                showlegend=(column==1),visible=(representation==transfer_reps[0]),
                error_y=dict(type="data",array=d[metric+"_sd"],visible=True),
                hovertemplate="labels=%{x}<br>mean=%{y:.3f}<extra>"+representation+" · "+relation+" · "+method+"</extra>"),1,column)
            trace_rep.append(representation)
for column in range(1,4): fig.update_xaxes(type="log",title="target labels",tickvals=[1,5,10,50,100],row=1,col=column)
fig.update_yaxes(title="R²",row=1,col=1);fig.update_yaxes(title="fF",row=1,col=2);fig.update_yaxes(title="fF",row=1,col=3)
buttons=[dict(label=representation,method="update",args=[{"visible":[value==representation for value in trace_rep]},{"title":"Few-shot transfer — "+representation}]) for representation in transfer_reps]
fig.update_layout(title="Few-shot transfer — "+transfer_reps[0],height=620,
    updatemenus=[dict(buttons=buttons,direction="down",x=1,xanchor="right")],legend=dict(orientation="h",y=-.23))
fig.show()
display(transfer_mean[transfer_mean.target_labels==100].round(4))
"""),
    md(r"""
### Physical reading of the transfer result

At one label, every method is unstable on average; v4 pooling is less poor but
still has negative mean `R²`. At 100 labels, target-only v4 reaches mean
`R² = 0.943`, RMSE `1.94 fF`, and MedAE `0.584 fF`, better than its pooled and
residual-transfer alternatives. These historical datasets therefore do **not**
support a universal transfer-win claim. The likely confound is that topology,
solver campaign, option vocabulary, and label range all change together.
"""),
    md(r"""
## 12. Is another topology worth more than another hundred familiar designs?

The generalist study holds the total training budget at 30, 100, 300, or 600
designs and changes how many families contribute those rows. Every model is
then evaluated on fixed, design-disjoint tests from all three families. A
one-family model is therefore penalized when it cannot extrapolate to the two
unseen topologies—which is exactly the capability a “generalist” is supposed
to have.

Compare curves at the same x coordinate. If the 2- or 3-family curve rises
above the 1-family curve, geometry diversity bought more generalization than
spending the same simulation budget densely inside one topology.
"""),
    code(r"""
growth=pd.read_csv(PREDICTIVE_DIR/"generalist_growth_diversity.csv")
growth_mean=growth.groupby(["representation","train_family_count","train_designs"]).agg(
    r2=("r2_log1p","mean"),r2_sd=("r2_log1p","std"),rmse=("rmse_fF","mean"),rmse_sd=("rmse_fF","std"),
    medae=("medae_fF","mean"),medae_sd=("medae_fF","std")).reset_index()
growth_reps=list(growth_mean.representation.unique());trace_rep=[]
fig=make_subplots(rows=1,cols=3,subplot_titles=tuple(label for _,label in metrics))
for representation in growth_reps:
    drep=growth_mean[growth_mean.representation==representation]
    for column,(metric,label) in enumerate(metrics,start=1):
        for family_count,d in drep.groupby("train_family_count"):
            d=d.sort_values("train_designs")
            fig.add_trace(go.Scatter(x=d.train_designs,y=d[metric],mode="lines+markers",
                name=f"{family_count} training families",legendgroup=str(family_count),showlegend=(column==1),
                visible=(representation==growth_reps[0]),error_y=dict(type="data",array=d[metric+"_sd"],visible=True),
                hovertemplate="designs=%{x}<br>mean=%{y:.3f}<extra>"+representation+f" · {family_count} families</extra>"),1,column)
            trace_rep.append(representation)
for column in range(1,4): fig.update_xaxes(type="log",title="total training designs",tickvals=[30,100,300,600],row=1,col=column)
fig.update_yaxes(title="R²",row=1,col=1);fig.update_yaxes(title="fF",row=1,col=2);fig.update_yaxes(title="fF",row=1,col=3)
buttons=[dict(label=representation,method="update",args=[{"visible":[value==representation for value in trace_rep]},{"title":"Generalist growth — "+representation}]) for representation in growth_reps]
fig.update_layout(title="Generalist growth — "+growth_reps[0],height=590,
    updatemenus=[dict(buttons=buttons,direction="down",x=1,xanchor="right")],legend=dict(orientation="h",y=-.18))
fig.show()
display(growth_mean[(growth_mean.train_family_count==3)&(growth_mean.train_designs==600)].round(4))
"""),
    md(r"""
### Physical reading of the generalist-growth result

Family diversity matters more than simply adding rows from one topology. With
600 designs from all three families, v3 and v4 reach mean cross-task log-`R²`
of **0.942** and **0.941**, versus **0.881** for v2. Increasing one-family data
alone does not rescue unseen-family performance. This supports a concrete data
acquisition rule: spend new simulations on topology diversity and crossed
physical controls before densely oversampling an existing family.
"""),
    md(r"""
## 13. Final stress test: a three-terminal device that was never in training

The joined GDS from Section 8 is absent from every historical two-terminal
training table. Before predicting any number, the representation must at least
discover the correct physical problem: three signal conductors plus ground,
hence a symmetric `4×4` operator. The heatmap is the deterministic 2-D proxy
emitted by v4.

This is a **structural zero-shot pass**, not a capacitance-accuracy result. The
missing measurement is explicit: we need a converged 3-D capacitance matrix for
this composite, followed by a small sweep, before zero-/few-shot predictive
claims can be scored.
"""),
    code(r"""
matrix=proxy["joined_three_terminal"]
node_labels=["left","shared","right","ground"]
fig=go.Figure(go.Heatmap(z=matrix,x=node_labels,y=node_labels,colorscale="RdBu",zmid=0,
    text=np.round(matrix,4),texttemplate="%{text}",colorbar=dict(title="proxy fF"),
    hovertemplate="%{y} ↔ %{x}<br>low-fidelity proxy=%{z:.6f} fF<extra></extra>"))
fig.update_layout(title="Unseen composite: complete conductor + ground operator",height=540)
fig.show()
print("STRUCTURAL PASS: arbitrary-terminal graph and 4×4 proxy emitted")
print("PREDICTIVE CLAIM: NOT TESTED — acquire a converged 3D capacitance matrix before scoring")
"""),
    md(r"""
## 14. A stricter audit: train on two topologies and predict the third

The earlier representation gates use no capacitance labels. We now ask a harder
downstream question: if the model sees two component families but not the third,
does the universal geometry interface support extrapolation? The same nonlinear
random-feature ridge head is used in every cell, and all preprocessing is fitted
on training rows only. We report `R²` in `log(1+C)`, RMS prediction error in fF,
and median absolute error in fF. High within-family scores in Section 9 do not
guarantee success here.
"""),
    code(r"""
class RFFRidge:
    def __init__(self,seed=SEED,features=128,alpha=.3): self.seed,self.features,self.alpha=seed,features,alpha
    def fit(self,X,y):
        self.mean=X.mean(0);self.scale=X.std(0);self.scale=np.where(self.scale>1e-6,self.scale,1)
        z=np.clip((X-self.mean)/self.scale,-8,8);rng=np.random.default_rng(self.seed)
        sample=z[rng.choice(len(z),size=min(1000,len(z)),replace=False)];pairs=len(sample)//2
        median=np.median(np.sum((sample[:pairs]-sample[pairs:2*pairs])**2,axis=1)) if pairs else 1
        self.W=rng.normal(scale=np.sqrt(1/max(median,1e-12)),size=(z.shape[1],self.features));self.b=rng.uniform(0,2*np.pi,self.features)
        phi=np.c_[z,np.sqrt(2/self.features)*np.cos(z@self.W+self.b)];D=np.c_[np.ones(len(phi)),phi]
        P=np.eye(D.shape[1])*self.alpha;P[0,0]=0;self.coef=np.linalg.solve(D.T@D+P,D.T@y);return self
    def predict(self,X):
        z=np.clip((X-self.mean)/self.scale,-8,8);phi=np.c_[z,np.sqrt(2/self.features)*np.cos(z@self.W+self.b)]
        return np.c_[np.ones(len(phi)),phi]@self.coef
def scores(y,predlog):
    pred=np.maximum(np.expm1(predlog),0);log=np.log1p(y)
    return {"R2_log":1-np.sum((log-predlog)**2)/np.sum((log-log.mean())**2),
            "RMSE_fF":np.sqrt(np.mean((y-pred)**2)),"MedAE_fF":np.median(np.abs(y-pred))}

if V4_BALANCED_PATH.is_file() and V3_BALANCED_PATH.is_file() and V2_BALANCED_PATH.is_file():
    v4=pd.read_parquet(V4_BALANCED_PATH).drop_duplicates("design_id")
    v3=pd.read_parquet(V3_BALANCED_PATH).drop_duplicates("design_id")
    v2=pd.read_parquet(V2_BALANCED_PATH).drop_duplicates("design_id")[["design_id","embedding"]]
    v3_part=v3[["design_id","embedding"]].rename(columns={"embedding":"embedding_v3"})
    v2_part=v2.rename(columns={"embedding":"embedding_v2"})
    data=v4.merge(v3_part,on="design_id").merge(v2_part,on="design_id")
    reps={"v2":np.vstack(data.embedding_v2),"v3 core":np.vstack(data.embedding_v3)[:,:V3_BLOCK_SLICES["fixed_stack_core"].stop],
          "v4 pair":np.vstack(data.embedding_v4_pair)}
    labels=data.component_name.to_numpy();y=data.mutual_fF.to_numpy(float);results=[]
    for rep,X in reps.items():
        for held in sorted(set(labels)):
            train=labels!=held;test=~train
            pred=RFFRidge().fit(X[train],np.log1p(y[train])).predict(X[test])
            results.append({"representation":rep,"held_out":held,**scores(y[test],pred)})
    heldout=pd.DataFrame(results)
    display(heldout.round(3))
    fig=make_subplots(rows=1,cols=3,subplot_titles=("R2 in log1p(C)","RMSE","Median absolute error"))
    for rep,d in heldout.groupby("representation"):
        fig.add_trace(go.Bar(x=d.held_out,y=d.R2_log,name=rep,legendgroup=rep),1,1)
        fig.add_trace(go.Bar(x=d.held_out,y=d.RMSE_fF,name=rep,legendgroup=rep,showlegend=False),1,2)
        fig.add_trace(go.Bar(x=d.held_out,y=d.MedAE_fF,name=rep,legendgroup=rep,showlegend=False),1,3)
    fig.update_yaxes(title="R2",row=1,col=1);fig.update_yaxes(title="fF",row=1,col=2);fig.update_yaxes(title="fF",row=1,col=3)
    fig.update_layout(title="Strict held-out-family capacitance audit",height=500,barmode="group")
    fig.show()
else:
    print("Balanced v2/v3/v4 tables are not all available; representation-only sections remain fully executable.")
"""),
    md(r"""
### Read this audit without moving the goalposts

v4 is not declared successful only when it wins a prediction cell. Its
representation claim rests on the frozen physical gates. The table below shows
signed changes relative to v2 and v3: positive `ΔR²` helps, while negative
`ΔRMSE` and `ΔMedAE` helps. Mixed results stay visible.

On this cohort v4 strongly repairs v2's held-out transverse-cross failure and
improves the Tee result. It also lowers Generalized-IDC absolute errors even
when a comparison metric moves less decisively. v3 remains the better
TransmonCross representation under this particular head, which is evidence
against claiming universal v4 predictive dominance. Repeated seeds, alternative
heads, and full capacitance matrices belong in the next experiment, not in a
post-hoc change to these representation thresholds.
"""),
    code(r"""
if "heldout" in globals():
    baseline=heldout.set_index(["representation","held_out"])
    comparisons=[]
    for reference in ["v2","v3 core"]:
        for held in sorted(set(heldout.held_out)):
            candidate=baseline.loc[("v4 pair",held)]
            control=baseline.loc[(reference,held)]
            comparisons.append({"reference":reference,"held_out":held,
                "delta_R2":candidate.R2_log-control.R2_log,
                "delta_RMSE_fF":candidate.RMSE_fF-control.RMSE_fF,
                "delta_MedAE_fF":candidate.MedAE_fF-control.MedAE_fF})
    display(pd.DataFrame(comparisons).round(3))
"""),
    md(r"""
## 15. What a device physicist can take away

### Supported by the present evidence

- v2's full vector is not an arbitrary-rotation-invariant representation.
- v3's invariant construction is numerically strong for two selected terminals,
  but its fixed three-role interaction/operator design is not arbitrary-terminal.
- v4 removes the terminal ceiling, preserves unmarked conductor islands,
  exposes a genuinely permutation-equivariant graph, and supplies reciprocal
  pair views with all-other-conductor context.
- The 144-layout supplied sample contains no empirical vector collisions, and
  the controlled v4 views pass the predeclared planar numerical gates.
- v4 supports physical graph composition and pose-matched difference analysis;
  naive fixed-vector addition is rejected by a `0.869` relative error.
- Diverse three-family training improves the generalist much more reliably than
  adding examples from one family alone.

### Still unsupported—and therefore not claimed

- Pooled layout vectors are not proven injective over all possible GDS.
- The boundary operator is not a substitute for a converged 3D solve.
- Historical datasets do not isolate embedding quality from solver, stack,
  boundary-condition, and meshing differences.
- Flip-chip and material-stack generalization remain untested by design.
- Geometry distance is only modestly correlated with capacitance difference.
- These historical labels do not show a universal few-shot transfer advantage.
- The unseen three-terminal composite passes structurally but has no
  high-fidelity solver matrix, so zero-shot capacitance accuracy is untested.

### The next simulation campaign that would close the physics gaps

Use one standardized solver, substrate/metal stack, boundary condition, and
mesh-convergence protocol for crossed sweeps of:

1. generalized IDC, asymmetric IDC, concentric, star, legacy IDC, transverse
   cross, and at least one pad/meander topology;
2. two-, three-, four-, eight-, and sixteen-conductor controls;
3. scale, pair gap, facing length/overlap, ground clearance, and a third-body
   screening coordinate;
4. exact pose duplicates as negative controls;
5. identical GDS rows at multiple solver fidelities.

The decisive addition is not just more scalar mutual-capacitance labels. Save
the full conductor-plus-ground capacitance matrix for the multi-terminal controls
and the unseen composite. Freeze leave-one-topology-out tests and nested
1/5/10/50/100-shot target subsets before those results arrive. Only after the
planar representation and full-matrix head pass should the same internal layer
IR be extended with JSON/XML mappings for plane height, material, and thickness.
"""),
    code(r"""
print("Numerical gate summary")
display(scorecard[["representation","numerical_gates_passed","numerical_gates_total",
                   "rotation_37_drift","sensitivity_to_nuisance","gap_spearman",
                   "arbitrary_terminal_contract"]].round(6))
subprocess.run([sys.executable,str(REPO/"scripts/export_tutorial24_figures.py")],check=True,cwd=REPO)
figure_manifest=json.loads((FIGURE_DIR/"manifest.json").read_text())
display(pd.DataFrame(figure_manifest["figures"])[["figure","status","output"]])
print("Publication PNGs exported to",FIGURE_DIR)
print("No Git repository, GitHub remote, or Hugging Face dataset was modified by executing this notebook.")
"""),
]

notebook = nbf.v4.new_notebook(cells=cells)
notebook["metadata"] = {
    "kernelspec": {"display_name": "SQuADDS Tutorial (uv)", "language": "python", "name": "squadds-tutorial"},
    "language_info": {"name": "python", "version": "3.11"},
}
OUTPUT.parent.mkdir(parents=True, exist_ok=True)
nbf.write(notebook, OUTPUT)
print(f"wrote {OUTPUT} ({len(cells)} cells)")
